port: 7055

listeners:

  # Tests the ability to create temporary files
  /testTemp:

    logOutput: true
    logCommand: true

    # Here we define our temporary files
    files:
      tmp1: |
        Just a temporary {{ .name }}!

    # Command to run, and list of arguments
    command: bash
    args:
      - -c
      - |
        set -ex

        # Retrieve the temporary file path in different ways
        cat $GTE_FILES_tmp1
        cat {{ (gte).files.tmp1 }}