port: 7055

listeners:

  # Listener with path parameter, which is accessible
  # via .param1
  /hello/:param1:

    # Returns the output of the command in the response
    returnOutput: true

    # Command to run, and list of arguments
    command: bash
    args:
      - -c
      # Expects a `name` field to be passed by query or body (JSON/Form)
      - |
        echo "Hello {{ .name | upper }}, with param {{ .param1 }}"
