port: 7055

defaults:
  logOutput: true
  logArgs: true
  logCommand: true
  returnOutput: true

  # The error handler will be triggered whenever a listener
  # fails to be executed.
  #
  # This error handler creates a file, which contains an error
  # message.
  errorHandler:
    command: bash
    args:
      - -c
      - |
        set -e
        # If a file name has been passed in the original headers, use it to stor
        # an error message, otherwise use a default path.
        fileName="{{ coalesce (get .args.__gteHeaders "x-err-file") "/tmp/errorHandlerLog" }}"
        echo "There has been an error!" > "$fileName"

listeners:

  # This listener will cause an error because of a bad exit code
  # Test with:
  # [500,ERR] curl "http://localhost:7055/crash"
  /crash:

    # Command to run, and list of arguments
    command: bash
    args:
      - -c
      - |
        echo "Oh no!"
        exit 1